# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tab_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_3.setMinimumSize(QtCore.QSize(0, 500))
        self.tab_3.setObjectName("tab_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uname_label = QtWidgets.QLabel(self.layoutWidget)
        self.uname_label.setObjectName("uname_label")
        self.horizontalLayout_3.addWidget(self.uname_label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pword_label = QtWidgets.QLabel(self.layoutWidget)
        self.pword_label.setObjectName("pword_label")
        self.horizontalLayout.addWidget(self.pword_label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login = QtWidgets.QPushButton(self.layoutWidget)
        self.login.setObjectName("login")
        self.horizontalLayout_4.addWidget(self.login)
        self.logout = QtWidgets.QPushButton(self.layoutWidget)
        self.logout.setObjectName("logout")
        self.horizontalLayout_4.addWidget(self.logout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.changePassButton = QtWidgets.QPushButton(self.layoutWidget)
        self.changePassButton.setObjectName("changePassButton")
        self.horizontalLayout_7.addWidget(self.changePassButton)
        self.switchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.switchButton.setObjectName("switchButton")
        self.horizontalLayout_7.addWidget(self.switchButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.tab_3.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.upload = QtWidgets.QPushButton(self.tab)
        self.upload.setMinimumSize(QtCore.QSize(120, 0))
        self.upload.setSizeIncrement(QtCore.QSize(0, 0))
        self.upload.setBaseSize(QtCore.QSize(0, 0))
        self.upload.setObjectName("upload")
        self.horizontalLayout_5.addWidget(self.upload)
        self.export_table = QtWidgets.QPushButton(self.tab)
        self.export_table.setMinimumSize(QtCore.QSize(120, 0))
        self.export_table.setSizeIncrement(QtCore.QSize(0, 0))
        self.export_table.setBaseSize(QtCore.QSize(0, 0))
        self.export_table.setObjectName("export_table")
        self.horizontalLayout_5.addWidget(self.export_table)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addRow = QtWidgets.QPushButton(self.tab)
        self.addRow.setObjectName("addRow")
        self.gridLayout_2.addWidget(self.addRow, 0, 0, 1, 1)
        self.addCol = QtWidgets.QPushButton(self.tab)
        self.addCol.setObjectName("addCol")
        self.gridLayout_2.addWidget(self.addCol, 0, 1, 1, 1)
        self.deleteRow = QtWidgets.QPushButton(self.tab)
        self.deleteRow.setObjectName("deleteRow")
        self.gridLayout_2.addWidget(self.deleteRow, 1, 0, 1, 1)
        self.deleteCol = QtWidgets.QPushButton(self.tab)
        self.deleteCol.setObjectName("deleteCol")
        self.gridLayout_2.addWidget(self.deleteCol, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tplChooseBrowser = QtWidgets.QLineEdit(self.tab)
        self.tplChooseBrowser.setEnabled(True)
        self.tplChooseBrowser.setObjectName("tplChooseBrowser")
        self.verticalLayout_5.addWidget(self.tplChooseBrowser)
        self.send_list = QtWidgets.QListWidget(self.tab)
        self.send_list.setProperty("isWrapping", False)
        self.send_list.setWordWrap(True)
        self.send_list.setObjectName("send_list")
        self.verticalLayout_5.addWidget(self.send_list)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.refreshTplButtion = QtWidgets.QPushButton(self.tab)
        self.refreshTplButtion.setObjectName("refreshTplButtion")
        self.horizontalLayout_6.addWidget(self.refreshTplButtion)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.tab_3.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.resultLine = QtWidgets.QLineEdit(self.tab_2)
        self.resultLine.setObjectName("resultLine")
        self.verticalLayout_6.addWidget(self.resultLine)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultTable = QtWidgets.QTableWidget(self.tab_2)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(0)
        self.resultTable.setRowCount(0)
        self.resultTable.horizontalHeader().setDefaultSectionSize(100)
        self.horizontalLayout_2.addWidget(self.resultTable)
        self.exportFile = QtWidgets.QPushButton(self.tab_2)
        self.exportFile.setObjectName("exportFile")
        self.horizontalLayout_2.addWidget(self.exportFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.tab_3.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.templateManageTable = QtWidgets.QTableWidget(self.tab_5)
        self.templateManageTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.templateManageTable.setObjectName("templateManageTable")
        self.templateManageTable.setColumnCount(0)
        self.templateManageTable.setRowCount(0)
        self.templateManageTable.horizontalHeader().setMinimumSectionSize(16)
        self.templateManageTable.horizontalHeader().setStretchLastSection(False)
        self.templateManageTable.verticalHeader().setDefaultSectionSize(36)
        self.templateManageTable.verticalHeader().setMinimumSectionSize(32)
        self.templateManageTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.templateManageTable)
        self.refreshButton = QtWidgets.QPushButton(self.tab_5)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout_8.addWidget(self.refreshButton)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.templateApplyText = QtWidgets.QTextEdit(self.tab_5)
        self.templateApplyText.setObjectName("templateApplyText")
        self.verticalLayout_7.addWidget(self.templateApplyText)
        self.addOneButton = QtWidgets.QPushButton(self.tab_5)
        self.addOneButton.setObjectName("addOneButton")
        self.verticalLayout_7.addWidget(self.addOneButton)
        self.templateApplyBrowser = QtWidgets.QTextEdit(self.tab_5)
        self.templateApplyBrowser.setObjectName("templateApplyBrowser")
        self.verticalLayout_7.addWidget(self.templateApplyBrowser)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.tab_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.historyTable = QtWidgets.QTableWidget(self.tab_6)
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(0)
        self.historyTable.setRowCount(0)
        self.historyTable.horizontalHeader().setCascadingSectionResizes(False)
        self.historyTable.horizontalHeader().setSortIndicatorShown(True)
        self.historyTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.historyTable)
        self.historyRefreshButton = QtWidgets.QPushButton(self.tab_6)
        self.historyRefreshButton.setObjectName("historyRefreshButton")
        self.verticalLayout_9.addWidget(self.historyRefreshButton)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tab_3.addTab(self.tab_6, "")
        self.verticalLayout_3.addWidget(self.tab_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.statusLine = QtWidgets.QTextBrowser(self.centralwidget)
        self.statusLine.setMaximumSize(QtCore.QSize(16777215, 40))
        self.statusLine.setTabStopWidth(40)
        self.statusLine.setObjectName("statusLine")
        self.gridLayout.addWidget(self.statusLine, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_3.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GroupMessageSystem by BITNP"))
        self.uname_label.setText(_translate("MainWindow", "Username"))
        self.pword_label.setText(_translate("MainWindow", "Password"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.logout.setText(_translate("MainWindow", "Logout"))
        self.changePassButton.setText(_translate("MainWindow", "ChangePassword"))
        self.switchButton.setText(_translate("MainWindow", "SwitchService"))
        self.tab_3.setTabText(self.tab_3.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.tableWidget.setSortingEnabled(True)
        self.upload.setText(_translate("MainWindow", "Upload"))
        self.export_table.setText(_translate("MainWindow", "Export"))
        self.addRow.setText(_translate("MainWindow", "AddaRow"))
        self.addCol.setText(_translate("MainWindow", "AddaColumn"))
        self.deleteRow.setText(_translate("MainWindow", "DeleteaRow"))
        self.deleteCol.setText(_translate("MainWindow", "DeleteaColumn"))
        self.refreshTplButtion.setText(_translate("MainWindow", "Refresh"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.pushButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.tab_3.setTabText(self.tab_3.indexOf(self.tab), _translate("MainWindow", "Single"))
        self.exportFile.setText(_translate("MainWindow", "Export"))
        self.tab_3.setTabText(self.tab_3.indexOf(self.tab_2), _translate("MainWindow", "Result"))
        self.templateManageTable.setSortingEnabled(True)
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.addOneButton.setText(_translate("MainWindow", "AddOne"))
        self.tab_3.setTabText(self.tab_3.indexOf(self.tab_5), _translate("MainWindow", "TemplateManagement"))
        self.historyTable.setSortingEnabled(True)
        self.historyRefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.tab_3.setTabText(self.tab_3.indexOf(self.tab_6), _translate("MainWindow", "History"))
        self.menu.setTitle(_translate("MainWindow", "NothingHere"))

