image: docker:latest

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

job1:
  tags: 
    - docker
  stage: build
  script:
    - docker build -t $IMAGE_TAG .

job2:
  tags: 
    - shell
  stage: deploy
  script:
    - echo $IMAGE_TAG
    - echo $RELEASE_TAG
    - docker info